version: "3.3"
services:
    gitea-server:
      image: gitea/gitea:1.15.7
      restart: always
      ports: 
        - 0.0.0.0:80:3000
      volumes:
        - type: bind
          source: /home/abay/data
          target: /data
      networks:
        - drone-net
    drone-server:
        image: drone/drone:1
        environment:
            - DRONE_GITEA_SERVER=http://127.0.0.1
            - DRONE_GITEA_CLIENT_ID=448ea62d-0250-4b20-8a1c-4112c55f0403
            - DRONE_GITEA_CLIENT_SECRET=LgjMwx0es66TqrqgK2ZJqb6KEIMojRzy9oo0ahgZ1s8u
            - DRONE_RPC_SECRET=1q2w3e4r
            - DRONE_SERVER_HOST=127.0.0.1:8080
            - DRONE_SERVER_PROTO=http
            - DRONE_WEBHOOK_SKIP_VERIFY=true
        restart: always
        ports: 
            - 0.0.0.0:8080:80
        networks:
            - drone-net
    drone-runner:
        image: drone/drone-runner-docker:1
        depends_on: 
            - drone-server
        environment:
            - DRONE_RPC_PROTO=http
            - DRONE_RPC_HOST=drone-server
            - DRONE_RPC_SECRET=1q2w3e4r
            - DRONE_RUNNER_CAPACITY=1
            - DRONE_RUNNER_NAME=drone-runner-1
        restart: always
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - drone-net
networks:
    drone-net: